// <copyright file="PostOperationleadCreate.cs" company="">
// Copyright (c) 2019 All Rights Reserved
// </copyright>
// <author></author>
// <date>11/9/2019 10:03:13 PM</date>
// <summary>Implements the PostOperationleadCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace DynamicsCRMExtension.PluginsExtention
{

    /// <summary>
    /// PostOperationleadCreate Plugin.
    /// </summary>    
    public class CreateTaskOnLeadCreate: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTaskOnLeadCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public CreateTaskOnLeadCreate(string unsecure, string secure)
            : base(typeof(CreateTaskOnLeadCreate))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }


            // Get Organization Service
            IOrganizationService service = localContext.OrganizationService;

            // Get Plugin Execution Context
            IPluginExecutionContext context = localContext.PluginExecutionContext;

            // Get Input Parameter
            if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)
            {
                Entity inputParameter = (Entity)context.InputParameters["Target"];

                Entity task = new Entity("task");
                task["subject"] = "Task From Lead";
                task["regardingobjectid"] = inputParameter;
                service.Create(task);

            }



                // TODO: Implement your custom Plug-in business logic.
            }
        }
}
